### ISSUE TITLE
Copy-CohesityMSSQLObject failing to create Sql Server Clone

### ISSUE THREAD

**Issue by twebster2** [cohesity/cohesity-powershell-module#173]
Since Release 163, when Copy-CohesityMSSQLObject was migrated from c# to powershell function I'm unable to create a sql server database clone. I recieve  this error:

`{"errorCode":"KInternalError","message":"Cannot find file with metadata contents needed for this restore"}
, MSSQLObject : Failed to copy.`

This seems to be due to the target host id being set in the wrong place in the request object.

Current:
```yaml
...
{
    "restoreParams":  {
                          "sqlRestoreParams":  {
                                                   "instanceName":  "MSSQLSERVER",
                                                   "newDatabaseName":  "CrmStoreClone",
                                                   "captureTailLogs":  false
                                               }
                      },
    "appEntity":  {
                      "id":  201,
                      "type":  3
                  },
    "targetHost":  {
                       "id":  212
                   }
}
...
```

Expected:
```yaml
...
{
    "restoreParams":  {
                          "sqlRestoreParams":  {
                                                   "instanceName":  "MSSQLSERVER",
                                                   "newDatabaseName":  "CrmStoreClone",
                                                   "captureTailLogs":  false
                                               },
                          "targetHost":  {
                                                  "id":  212
                                               }
                      },
    "appEntity":  {
                      "id":  201,
                      "type":  3
                  }
}
```

i.e within the restoreParams object rather than the parent object.
Issue on line 128 & 131 of https://github.com/cohesity/cohesity-powershell-module/blob/master/src/Cohesity.Powershell/Scripts/Clone/Copy-CohesityMSSQLObject.ps1
